### ISSUE TITLE
Project plan

### ISSUE THREAD

**Issue by ddesai2000** [stat231-f21/blog_shiny-sea-turtles#1]
**Do you plan for your final project to be an extension of the mid-semester project?** NO

**If No: Include details regarding the new general topic / phenomena you want to explore and the questions you hope to address. Identify reasonable data sources and how you will acquire the data (web scrape? download? specific packages? API?).**

For our final blog project, our group wanted to explore something different than our salmon database. While our salmon exploration was informative about the general state of the salmon fishery and what it implies for economic and ecological health around the world, we wanted to expand our globalization to a different topic. We realized that apart from environmental causes and economics, we have a collective affinity for entertainment. With seasonal buzz around movies and TV shows on Netflix (like the current widespread interest for the TV show “Squid Game”), we aim to analyze and visualize some of the most popular recent releases. The variables we are using are from two different datasets, one that has more general information pertaining to Netflix - like the subscriber count by country and total revenue by country - and one that contains information on individual titles, such as the names of directors and actors, and a short description of the title. We will use these variables to create map, text analysis and network visualizations. 

The questions we plan to address are:
* Which actors work together the most on shows/movies on Netflix?
* What are the most popular keywords in descriptions of Netflix shows?
* Which countries does Netflix have the most viewers in, and how does that compare to where Netflix makes its shows?
* What are the most popular Netflix shows, and do they have any traits (genre, cast, director, etc.) in common? 

Our data will be collected from multiple sources, including Kaggle (https://www.kaggle.com/shivamb/netflix-shows), Comparitech (https://www.comparitech.com/tv-streaming/netflix-subscribers/), and Whats-on-Netflix (https://www.whats-on-netflix.com/news/every-viewing-statistic-netflix-has-released-so-far-october-2021/). The Kaggle data is fairly clean and in a .csv file, displaying details about Netflix shows added to the platform since 2011. The Comparitech site has a table of Netflix revenue and viewers by country, so we will have to scrape that table into R. The Whats-on-Netflix site has the number of viewers by Netflix show, and we will have to scrape the viewership per show since it is not formatted in a table. 

**Describe what you hope to deliver as a final product. Will your blog include a published Shiny application? Will it incorporate an interactive map? Will it involve a predictive model that forecasts future values of some quantity using data that you’ve integrated?**

Since our database contains information about genre, director, cast, date, country, title, and description, we are considering a shiny app component as well as some of the new visualizations we learned this year. 

For a network visualization, we wanted to create a network connecting the cast members who worked together throughout the entire database to see if there were any trends between the genre or directors. For example, in every Adam Sandler film, there are always the same group of actors. And in Michael Bay films, there is always Megan Fox. Perhaps this network can shed light on any of those connections between actors and genre or actors and directors. 

Our main database also contains the country in which the film was produced. Using the data from Comparitech on subscribers by country, for another visualization, we hoped to make an interactive map combining information from our main database with this website’s viewership data per country. For example, if we hover over a country, it can show us the total number of subscribers as of 2020, as well as what proportion of the films in our main database were produced there. 

Yet another visualization we are considering is a text analysis based on the description of the title. We may be interested in seeing what words are used the most in common amongst the different descriptions (other than stop words, of course!) and what this implies about the general tone of Netflix produced titles. 

Our shiny app will include a table of the movies and tv shows from our main dataset from Kaggle, and we will add widgets to make this table extremely user friendly and filterable in order to let users search by cast, year, genre, show/movie name, director, description of show/movie to help them find a show/movie to watch.  

**Outline a schedule for your group’s progress that will take you from now (ideas phase) to final blog post and presentation at the end of the semester. During the last project, we had specific checkpoints for different phases of the project. Based on what you envision for your final blog post, identify checkpoints for your group and dates by which you plan to reach those checkpoints. Hold each other accountable, so you’re not waiting until the last minute to do things! In particular, you should have at least one checkpoint each week (ideally two) identifying what work you expect to complete by then.** 

* 11/5
  + Start wrangling and scraping the data
  + Assign each person one new visualization to focus on 
* 11/8
  + Finish wrangling and have datasets ready to make visualizations
  + Start code for visualizations
* 11/12
  + Continue code for visualizations, think about shiny app 
  + Have a basic network, map, and word cloud
* 11/15
  + Finish up code for visualizations (and shiny app), start writeups
* 11/19 (thanksgiving start)
  + Finish up code for visualizations, work on writeups
* 11/22 (during thanksgiving)
  + Writeups + prepare for presentation
* 11/26 (during thanksgiving)
  + Writeups + prepare for presentation
* 11/29
  + Final touches for presentation
* 12/3
  + Edit blog as necessary based on presentation feedback
* 12/6
  + Edit blog as necessary based on presentation feedback

**Comment by bebailey** [comment]
This was not part of the requirement, but please make sure you discuss amongst yourselves exactly how you plan to divide up the work. Perhaps it would be useful to write it down as a sort of group contract, even (it sounds like you are planning to have that discussion). To the degree possible, we want equitable contributions to the core components of the blog, with flexibility for any individual to go "above and beyond" on any particular aspect of interest to them. 

---

To embed a shiny app, you can use a code chunk (see [this link](https://bookdown.org/yihui/bookdown/web-pages-and-shiny-apps.html) for details):

```
knitr::include_app("https://your-account.shinyapps.io/your-app/", height = "600px")
```

**Comment by succulentoctopus** [comment]
Status Update 11/09:
At this point, all three group members have their data wrangled and ready for visualizations. Two of the three visualizations have already been coded preliminarily, while the code for the third is expected to be finished by Friday, putting us ahead of schedule. Our goals for the coming weeks include finishing all three visualizations and adding more aesthetically pleasing features, as well as considering the table for our embedded Shiny app.

**Comment by succulentoctopus** [comment]
Status update 11/16: 
Our three main visualizations have been created, and the code for each has been updated and pushed, and our data wrangling code has been updated and finalized. We are now working on getting the visualizations into the blog, and also making a few additional visualizations to embed via Shiny App. We are just about on schedule, with the last two components we need to do being the Shiny App code and our writeups for the blog. We anticipate being done with both by the end of next week.
